<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Ben Anderson" />


<title>UK Electricity Generation and Carbon Itensity</title>

<script src="covidLockdown_UK_upTo_2020-06-01_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="covidLockdown_UK_upTo_2020-06-01_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="covidLockdown_UK_upTo_2020-06-01_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="covidLockdown_UK_upTo_2020-06-01_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="covidLockdown_UK_upTo_2020-06-01_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="covidLockdown_UK_upTo_2020-06-01_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="covidLockdown_UK_upTo_2020-06-01_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="covidLockdown_UK_upTo_2020-06-01_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="covidLockdown_UK_upTo_2020-06-01_files/navigation-1.1/tabsets.js"></script>
<script src="covidLockdown_UK_upTo_2020-06-01_files/navigation-1.1/codefolding.js"></script>
<link href="covidLockdown_UK_upTo_2020-06-01_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="covidLockdown_UK_upTo_2020-06-01_files/highlightjs-9.12.0/highlight.js"></script>
<script src="covidLockdown_UK_upTo_2020-06-01_files/kePrint-0.0.1/kePrint.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">UK Electricity Generation and Carbon Itensity</h1>
<h3 class="subtitle">covid 19 lockdown v1.0</h3>
<h4 class="author">Ben Anderson</h4>
<h4 class="date">Last run at: 2020-06-17 16:31:44</h4>

</div>


<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>Building on <span class="citation">(Staffell 2017)</span> and <span class="citation">(Khan, Jack, and Stephenson 2018)</span>, we are interested in GHG emissions from UK electricity generation over time. We are especially interested in how this might change during the UK covid-19 <a href="https://www.nationalgrideso.com/news/lockdown-effect-tv-viewing-habits-and-electricity-grid">lockdown period</a> (from ).</p>
<p>Several articles by ythe UK ESO and others have already explored this topic:</p>
<ul>
<li><a href="https://www.nationalgrideso.com/news/lockdown-effect-tv-viewing-habits-and-electricity-grid" class="uri">https://www.nationalgrideso.com/news/lockdown-effect-tv-viewing-habits-and-electricity-grid</a></li>
<li><a href="https://www.nationalgrideso.com/news/planning-easter-during-coronavirus-outbreak" class="uri">https://www.nationalgrideso.com/news/planning-easter-during-coronavirus-outbreak</a></li>
<li><a href="https://theconversation.com/we-analysed-electricity-demand-and-found-coronavirus-has-turned-weekdays-into-weekends-134606" class="uri">https://theconversation.com/we-analysed-electricity-demand-and-found-coronavirus-has-turned-weekdays-into-weekends-134606</a></li>
</ul>
<p>Fortunately the UK Electricity System Operator publishes <a href="https://data.nationalgrideso.com/carbon-intensity1/historic-generation-mix/r/historic_gb_generation_mix">half-hourly generation data</a> which includes both power generation (and thus 'demand') by fuels and also includes a per-kWh <a href="https://carbonintensity.org.uk/">carbon intensity</a> for the electricity produced per half-hour. We use this data to explore the following research questions:</p>
<ul>
<li><p>To what extent has electricty demand shown deviation from 'normal' demand patterns during the lockdown period?</p></li>
<li><p>Has the composition of fuel sources supplying electriicty changed during this period?</p></li>
<li><p>Has the lockdown changed greenhouse-gas emissions associated with electriicty generation?</p></li>
</ul>
</div>
<div id="data" class="section level1">
<h1><span class="header-section-number">2</span> Data</h1>
<div id="genData" class="section level2">
<h2><span class="header-section-number">2.1</span> Grid generation data</h2>
<p>This is 'grid' generation from major power stations of various kinds. Data downloaded from <code>https://data.nationalgrideso.com/carbon-intensity1/historic-generation-mix/r/historic_gb_generation_mix</code> and pre-processed.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:testGrid">Table 2.1: </span>Grid gen data (first 6 rows)
</caption>
<thead>
<tr>
<th style="text-align:left;">
DATETIME
</th>
<th style="text-align:right;">
year
</th>
<th style="text-align:left;">
rDateTimeUTC
</th>
<th style="text-align:right;">
GENERATION
</th>
<th style="text-align:right;">
CARBON_INTENSITY
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2016-01-01 00:00:00
</td>
<td style="text-align:right;">
2016
</td>
<td style="text-align:left;">
2016-01-01 00:00:00
</td>
<td style="text-align:right;">
28789
</td>
<td style="text-align:right;">
249
</td>
</tr>
<tr>
<td style="text-align:left;">
2016-01-01 00:30:00
</td>
<td style="text-align:right;">
2016
</td>
<td style="text-align:left;">
2016-01-01 00:30:00
</td>
<td style="text-align:right;">
29372
</td>
<td style="text-align:right;">
262
</td>
</tr>
<tr>
<td style="text-align:left;">
2016-01-01 01:00:00
</td>
<td style="text-align:right;">
2016
</td>
<td style="text-align:left;">
2016-01-01 01:00:00
</td>
<td style="text-align:right;">
29468
</td>
<td style="text-align:right;">
275
</td>
</tr>
<tr>
<td style="text-align:left;">
2016-01-01 01:30:00
</td>
<td style="text-align:right;">
2016
</td>
<td style="text-align:left;">
2016-01-01 01:30:00
</td>
<td style="text-align:right;">
28745
</td>
<td style="text-align:right;">
277
</td>
</tr>
<tr>
<td style="text-align:left;">
2016-01-01 02:00:00
</td>
<td style="text-align:right;">
2016
</td>
<td style="text-align:left;">
2016-01-01 02:00:00
</td>
<td style="text-align:right;">
27736
</td>
<td style="text-align:right;">
278
</td>
</tr>
<tr>
<td style="text-align:left;">
2016-01-01 02:30:00
</td>
<td style="text-align:right;">
2016
</td>
<td style="text-align:left;">
2016-01-01 02:30:00
</td>
<td style="text-align:right;">
27045
</td>
<td style="text-align:right;">
277
</td>
</tr>
</tbody>
</table>
<p>Note that according to the dataset <a href="https://data.nationalgrideso.com/carbon-intensity1/historic-generation-mix/r/historic_gb_generation_mix">source</a>:</p>
<ul>
<li>&quot;Data points are either MW or %&quot;. This may be <code>mean MW</code> over the half hour or it may mean <code>MWh per half-hour</code>. It is unclear. The % refers to the fuel mix. Which one could easily calculate from the MW values. But anyway...</li>
<li>carbon intensity is helpfully described as <em>&quot;The carbon intensity of electricity is a measure of how much Carbon dioxide emissions are produced per kilowatt hour of electricity consumed.&quot;</em>. However we assume it is gCO2e/kWh - based on <a href="https://carbonintensity.org.uk/" class="uri">https://carbonintensity.org.uk/</a></li>
</ul>
<p>Table <a href="#tab:descData">2.2</a> shows the mean half hourly generation (MW) and mean carbon intensity over the years covered by the data. It also shows the implied mean half-hourly total kg CO2e per half hour which we have calculated as follows: {#kgcalc} * convert <code>GENERATION</code> (MW) to MWh per half hour by <code>GENERATION/2</code> (1 MW for half an hour = 1/2 MWh) * convert the result to kWh (<code>* 10000</code>) * multiply by the <code>CARBON_INTENSITY</code> which is in gCO2e/kWh * divide by 1000 to get Kg</p>
<p>Yes, we have *1000 and then /1000 which is 1 but for the sake of clarity we have kept all the steps.</p>
<blockquote>
<p>NB: we are unclear how generation via interconnect is included in the original carbon intensity calculation but note that the <a href="https://github.com/carbon-intensity/methodology/raw/master/Carbon%20Intensity%20Forecast%20Methodology.pdf">ESO forecast methodology document</a> states that it is.</p>
</blockquote>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:descData">Table 2.2: </span>Descriptive stats by year - note that 2020 is incomplete
</caption>
<thead>
<tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:right;">
Total annual CO2e (MtCO2e, DBEIS)
</th>
<th style="text-align:right;">
Total annual CO2e (MtCO2e, calculated)
</th>
<th style="text-align:right;">
Mean halfhourly CO2e (tCO2e, calculated)
</th>
<th style="text-align:right;">
Mean half-hourly carbon intensity (gCO2e/kWh)
</th>
<th style="text-align:right;">
Mean halfhourly generation (GWh)
</th>
<th style="text-align:right;">
Total annual generation (TWh)
</th>
<th style="text-align:left;">
Max date in range
</th>
<th style="text-align:right;">
nObs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2016
</td>
<td style="text-align:right;">
83.0
</td>
<td style="text-align:right;">
92.25
</td>
<td style="text-align:right;">
5265.32
</td>
<td style="text-align:right;">
299.36
</td>
<td style="text-align:right;">
34.13
</td>
<td style="text-align:right;">
298.99
</td>
<td style="text-align:left;">
2016-12-31
</td>
<td style="text-align:right;">
17520
</td>
</tr>
<tr>
<td style="text-align:right;">
2017
</td>
<td style="text-align:right;">
73.1
</td>
<td style="text-align:right;">
81.02
</td>
<td style="text-align:right;">
4637.35
</td>
<td style="text-align:right;">
262.87
</td>
<td style="text-align:right;">
33.96
</td>
<td style="text-align:right;">
296.63
</td>
<td style="text-align:left;">
2017-12-31
</td>
<td style="text-align:right;">
17472
</td>
</tr>
<tr>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
66.8
</td>
<td style="text-align:right;">
71.91
</td>
<td style="text-align:right;">
4115.64
</td>
<td style="text-align:right;">
234.84
</td>
<td style="text-align:right;">
33.88
</td>
<td style="text-align:right;">
296.00
</td>
<td style="text-align:left;">
2018-12-31
</td>
<td style="text-align:right;">
17472
</td>
</tr>
<tr>
<td style="text-align:right;">
2019
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
64.03
</td>
<td style="text-align:right;">
3664.67
</td>
<td style="text-align:right;">
214.15
</td>
<td style="text-align:right;">
33.28
</td>
<td style="text-align:right;">
290.72
</td>
<td style="text-align:left;">
2019-12-31
</td>
<td style="text-align:right;">
17472
</td>
</tr>
<tr>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
22.14
</td>
<td style="text-align:right;">
3054.43
</td>
<td style="text-align:right;">
184.08
</td>
<td style="text-align:right;">
32.23
</td>
<td style="text-align:right;">
116.82
</td>
<td style="text-align:left;">
2020-05-31
</td>
<td style="text-align:right;">
7248
</td>
</tr>
</tbody>
</table>
<p>As we can see mean half-hourly generation has declined over the years but much less spectacularly than the mean carbon intensity which decreased by 61 from 2017 to 2020.</p>
<p>Table of peak periods</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:peakPeriodsTable">Table 2.3: </span>Monthly total TWh generation by year - note that 2020 is incomplete
</caption>
<thead>
<tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:right;">
Early morning
</th>
<th style="text-align:right;">
Morning peak
</th>
<th style="text-align:right;">
Day time
</th>
<th style="text-align:right;">
Evening peak
</th>
<th style="text-align:right;">
Late evening
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2016
</td>
<td style="text-align:right;">
5.83
</td>
<td style="text-align:right;">
1.62
</td>
<td style="text-align:right;">
8.78
</td>
<td style="text-align:right;">
4.82
</td>
<td style="text-align:right;">
3.87
</td>
<td style="text-align:right;">
24.92
</td>
</tr>
<tr>
<td style="text-align:right;">
2017
</td>
<td style="text-align:right;">
5.77
</td>
<td style="text-align:right;">
1.60
</td>
<td style="text-align:right;">
8.72
</td>
<td style="text-align:right;">
4.79
</td>
<td style="text-align:right;">
3.84
</td>
<td style="text-align:right;">
24.72
</td>
</tr>
<tr>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
5.77
</td>
<td style="text-align:right;">
1.60
</td>
<td style="text-align:right;">
8.73
</td>
<td style="text-align:right;">
4.75
</td>
<td style="text-align:right;">
3.81
</td>
<td style="text-align:right;">
24.67
</td>
</tr>
<tr>
<td style="text-align:right;">
2019
</td>
<td style="text-align:right;">
5.67
</td>
<td style="text-align:right;">
1.58
</td>
<td style="text-align:right;">
8.57
</td>
<td style="text-align:right;">
4.65
</td>
<td style="text-align:right;">
3.76
</td>
<td style="text-align:right;">
24.23
</td>
</tr>
<tr>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
5.51
</td>
<td style="text-align:right;">
1.47
</td>
<td style="text-align:right;">
8.18
</td>
<td style="text-align:right;">
4.53
</td>
<td style="text-align:right;">
3.68
</td>
<td style="text-align:right;">
23.36
</td>
</tr>
</tbody>
</table>
<p>Fuel trend plots by peak period</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/fuelTrendsPeakPeriod-1.png" width="672" /></p>
<pre><code>## Saving 10 x 5 in image
## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p>Repeat using openair::smoothTrend() for de-seasoning and other benefits. NB: deaseasoning produces -ve values for coal :-)</p>
<p><img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/stFuelTrendsPeakPeriod-1.png" width="672" /></p>
<pre><code>## png 
##   2</code></pre>
</div>
<div id="embedded-generation-data" class="section level2">
<h2><span class="header-section-number">2.2</span> Embedded generation data</h2>
<p>Essentially 'non-grid' generation from solar photovoltaic and small scale wind which is 'embedded' - i.e. non-grid connected as it is connected 'downstream' of the grid exit points. We are not entirely sure if this is accounted for in the grid dataset or not.</p>
<blockquote>
<p>We have not yet found a source of this data (if we even need it).</p>
</blockquote>
<blockquote>
<p>For now embedded generation data is probably <em>not</em> included in the following analysis but we would expect it to depress grid demand when there is greatest insolation (middle of the day, obvs) and wind (largely random in the UK?).</p>
</blockquote>
</div>
</div>
<div id="analysis" class="section level1">
<h1><span class="header-section-number">3</span> Analysis</h1>
<p>In this section we analyse changes in electricity demand and associated carbon emissions during the UK Covid-19 lockdown via analysis of the generation data.</p>
<div id="generation-analysing-deviation-from-normal" class="section level2">
<h2><span class="header-section-number">3.1</span> Generation: Analysing deviation from 'normal'</h2>
<p>Several <a href="https://theconversation.com/we-analysed-electricity-demand-and-found-coronavirus-has-turned-weekdays-into-weekends-134606">articles</a> and <a href="https://twitter.com/DrIAGWilson/status/1255100828781883394">analyses</a> have suggested that demand (and thus generation) patterns have shifted so that <a href="http://www.ukerc.ac.uk/news/covid-lockdown-electricity-demand.html">weekdays have become more like weekends</a>.</p>
<div id="overall-trends" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Overall trends</h3>
<p>Figure <a href="#fig:TheilSenGWhPlot">3.1</a> uses the openair <code>TheilSen()</code> function <span class="citation">(Carslaw and Ropkins 2012)</span> to create a de-seasoned trend plot for mean monthly half-hourly (i.e. the mean of all half-hourly GW values for each month) generation in GW split by peak period (07:00 - 08:30 and 16:00 - 20:00) .</p>
<p>These plots show that there has been a steady decline of ~ 0.4 - 0.5 GW mean half hourly generation (and thus demand) per year since 2016 in each time period. The substantial below-trend fall in generation during lockdown in early Spring 2020 is clear, especailly for the morning peak, day-time and, to a lesser extent, evening peak periods. There appears to have been a smaller below-trend reduction at other times as we would expect. We can also see a notable drop in generation in late 2015 which was <a href="https://www.metoffice.gov.uk/binaries/content/assets/metofficegovuk/pdf/weather/learn-about/uk-past-events/state-of-uk-climate/mo-state-of-uk-climate-2015-v3.pdf">unusually warm and wet</a>.</p>
<blockquote>
<p>use mean of half-hourly GWh otherwise the periods with more half-hours tend to visually dominate</p>
</blockquote>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:TheilSenGWhPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/TheilSenGWhPlot-1.png" alt="Theil-Sen plot of mean half-hourly generation per month since 2016-01-01" width="672" />
<p class="caption">
Figure 3.1: Theil-Sen plot of mean half-hourly generation per month since 2016-01-01
</p>
</div>
<pre><code>## png 
##   2</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:TheilSenGWhPlot">Table 3.1: </span>Mean half-hourly GWh by year and peak period - 2020 incomplete
</caption>
<thead>
<tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:right;">
Early morning
</th>
<th style="text-align:right;">
Morning peak
</th>
<th style="text-align:right;">
Day time
</th>
<th style="text-align:right;">
Evening peak
</th>
<th style="text-align:right;">
Late evening
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2016
</td>
<td style="text-align:right;">
13.69
</td>
<td style="text-align:right;">
17.72
</td>
<td style="text-align:right;">
19.25
</td>
<td style="text-align:right;">
19.79
</td>
<td style="text-align:right;">
15.90
</td>
</tr>
<tr>
<td style="text-align:right;">
2017
</td>
<td style="text-align:right;">
13.58
</td>
<td style="text-align:right;">
17.61
</td>
<td style="text-align:right;">
19.17
</td>
<td style="text-align:right;">
19.73
</td>
<td style="text-align:right;">
15.83
</td>
</tr>
<tr>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
13.58
</td>
<td style="text-align:right;">
17.62
</td>
<td style="text-align:right;">
19.19
</td>
<td style="text-align:right;">
19.59
</td>
<td style="text-align:right;">
15.71
</td>
</tr>
<tr>
<td style="text-align:right;">
2019
</td>
<td style="text-align:right;">
13.36
</td>
<td style="text-align:right;">
17.32
</td>
<td style="text-align:right;">
18.83
</td>
<td style="text-align:right;">
19.15
</td>
<td style="text-align:right;">
15.51
</td>
</tr>
<tr>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
13.03
</td>
<td style="text-align:right;">
16.20
</td>
<td style="text-align:right;">
18.05
</td>
<td style="text-align:right;">
18.74
</td>
<td style="text-align:right;">
15.25
</td>
</tr>
</tbody>
</table>
<p>Use the openair results object to estimate what the 2020 values would have been if the deaseasoned trend slope had continued.</p>
<blockquote>
<p>need to use the Theil-Sen slope model to estimate what the values would have been</p>
</blockquote>
<pre><code>## Saving 7 x 5 in image</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:calculateGWhDiffFromTrend">Table 3.2: </span>GWh above/below expected mean half-hourly GWh by month
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
diff_Early morning
</th>
<th style="text-align:right;">
diff_Morning peak
</th>
<th style="text-align:right;">
diff_Day time
</th>
<th style="text-align:right;">
diff_Evening peak
</th>
<th style="text-align:right;">
diff_Late evening
</th>
<th style="text-align:right;">
diffTotal
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
-0.05
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
-0.15
</td>
<td style="text-align:right;">
-0.53
</td>
<td style="text-align:right;">
-0.34
</td>
<td style="text-align:right;">
-1.06
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-0.16
</td>
<td style="text-align:right;">
-0.35
</td>
<td style="text-align:right;">
-0.21
</td>
<td style="text-align:right;">
-0.60
</td>
<td style="text-align:right;">
-0.34
</td>
<td style="text-align:right;">
-1.65
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
-0.11
</td>
<td style="text-align:right;">
-0.44
</td>
<td style="text-align:right;">
-0.18
</td>
<td style="text-align:right;">
-0.35
</td>
<td style="text-align:right;">
-0.33
</td>
<td style="text-align:right;">
-1.41
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
-2.00
</td>
<td style="text-align:right;">
-3.60
</td>
<td style="text-align:right;">
-2.93
</td>
<td style="text-align:right;">
-2.05
</td>
<td style="text-align:right;">
-1.60
</td>
<td style="text-align:right;">
-12.18
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
-1.29
</td>
<td style="text-align:right;">
-2.63
</td>
<td style="text-align:right;">
-2.23
</td>
<td style="text-align:right;">
-1.70
</td>
<td style="text-align:right;">
-1.11
</td>
<td style="text-align:right;">
-8.97
</td>
</tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:calculateGWhDiffFromTrend">Table 3.2: </span>% above/below expected mean half-hourly GWh by month
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
pcDiff_Early morning
</th>
<th style="text-align:right;">
pcDiff_Morning peak
</th>
<th style="text-align:right;">
pcDiff_Day time
</th>
<th style="text-align:right;">
pcDiff_Evening peak
</th>
<th style="text-align:right;">
pcDiff_Late evening
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
-0.38
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
-0.80
</td>
<td style="text-align:right;">
-2.77
</td>
<td style="text-align:right;">
-2.25
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-1.20
</td>
<td style="text-align:right;">
-2.05
</td>
<td style="text-align:right;">
-1.11
</td>
<td style="text-align:right;">
-3.16
</td>
<td style="text-align:right;">
-2.22
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
-0.86
</td>
<td style="text-align:right;">
-2.58
</td>
<td style="text-align:right;">
-0.98
</td>
<td style="text-align:right;">
-1.84
</td>
<td style="text-align:right;">
-2.16
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
-15.23
</td>
<td style="text-align:right;">
-21.17
</td>
<td style="text-align:right;">
-15.74
</td>
<td style="text-align:right;">
-10.83
</td>
<td style="text-align:right;">
-10.51
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
-9.86
</td>
<td style="text-align:right;">
-15.48
</td>
<td style="text-align:right;">
-12.02
</td>
<td style="text-align:right;">
-8.98
</td>
<td style="text-align:right;">
-7.32
</td>
</tr>
</tbody>
</table>
<p>Theil-Sen by weekday (for fun):</p>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<p><img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/theilSenGWhDoWPlot-1.png" width="672" /></p>
</div>
<div id="half-hourly-patterns" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Half hourly patterns</h3>
<p>Figure <a href="#fig:recentDateTimeGWhPlot">3.2</a> shows total half-hourly generation since 2020-02-01. Overall generation has fallen as we would expect given the season (less heating and lighting required) and weekdays are indeed less easy to distinguish from weekends.</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:recentDateTimeGWhPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/recentDateTimeGWhPlot-1.png" alt="Half-hourly generation, UK (recent)" width="672" />
<p class="caption">
Figure 3.2: Half-hourly generation, UK (recent)
</p>
</div>
<p>Figure <a href="#fig:recentHalfHourlyProfileGWhPlot">3.3</a> shows the daily generation profiles over time for each day of the week. Clearly the shapes are both reducing in magnitude (seasonal and lockdown effects) and also converging in shape.</p>
<div class="figure"><span id="fig:recentHalfHourlyProfileGWhPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/recentHalfHourlyProfileGWhPlot-1.png" alt="Half-hourly generation, UK (recent)" width="672" />
<p class="caption">
Figure 3.3: Half-hourly generation, UK (recent)
</p>
</div>
<p>Figure <a href="#fig:makeWeekDayGWhPlot">3.4</a> shows the mean half-hourly GWh per day. Need to bear in mind the trends identified above.</p>
<pre><code>## Saving 9 x 5 in image</code></pre>
<div class="figure"><span id="fig:makeWeekDayGWhPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/makeWeekDayGWhPlot-1.png" alt="Half-hourly GWh" width="672" />
<p class="caption">
Figure 3.4: Half-hourly GWh
</p>
</div>
<p>Figure <a href="#fig:makeWeekdayTimeGWhPlot">3.5</a> shows the mean half-hourly CO2e per half-hour of each day. This plot shows the values as a proportion of the sum of the means across all half hours of each day to illustrate the relative, rather than absolute, shift in generation.</p>
<pre><code>## Saving 9 x 5 in image</code></pre>
<div class="figure"><span id="fig:makeWeekdayTimeGWhPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/makeWeekdayTimeGWhPlot-1.png" alt="% half-hourly GWh" width="672" />
<p class="caption">
Figure 3.5: % half-hourly GWh
</p>
</div>
<p>Figure <a href="#fig:timeVariationGWhDetailed">3.6</a> shows the difference between hourly and weekday patterns for lockdown 2020 and the same period in all years from 2018 onwards. It is interesting to note that the twin peak demand periods have been maintained during lockdown but they are considerably lower although we should expect some 'natural' reduction due to the overall downward generation trend shown in Figure <a href="#fig:TheilSenGWhPlot">3.1</a>. The lower middle monthly plot suggests that while lockdown caused a considerable drop in generation, this difference is now starting to converge on 'normal' seasonal demand levels.</p>
<pre><code>## Warning in checkPrep(mydata, vars, type, remove.calm = FALSE): Detected data with Daylight Saving
## Time, converting to UTC/GMT</code></pre>
<pre><code>## Warning: removing 96 missing rows due to plotPeriodDetailed</code></pre>
<div class="figure"><span id="fig:timeVariationGWhDetailed"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/timeVariationGWhDetailed-1.png" alt="timeVariation plots for half-hourly GW generation comparing pre/lockdown 2020 with the same months in previous years starting in 2018" width="672" />
<p class="caption">
Figure 3.6: timeVariation plots for half-hourly GW generation comparing pre/lockdown 2020 with the same months in previous years starting in 2018
</p>
</div>
<p>Repeat but less detail.</p>
<pre><code>## Warning in checkPrep(mydata, vars, type, remove.calm = FALSE): Detected data with Daylight Saving
## Time, converting to UTC/GMT</code></pre>
<div class="figure"><span id="fig:timeVariationGWh"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/timeVariationGWh-1.png" alt="timeVariation plots for half-hourly GWh generation comparing pre/lockdown 2020 up to 2020-06-01" width="672" />
<p class="caption">
Figure 3.7: timeVariation plots for half-hourly GWh generation comparing pre/lockdown 2020 up to 2020-06-01
</p>
</div>
<pre><code>## Confirming dates plotted: date (as set for openair)</code></pre>
<pre><code>##                  Min.               1st Qu.                Median                  Mean 
## &quot;2017-01-05 00:00:00&quot; &quot;2017-11-11 17:37:30&quot; &quot;2018-09-18 12:15:00&quot; &quot;2018-09-18 10:56:48&quot; 
##               3rd Qu.                  Max. 
## &quot;2019-07-26 05:52:30&quot; &quot;2020-05-31 23:30:00&quot;</code></pre>
<pre><code>## Confirming dates plotted: dateFixed</code></pre>
<pre><code>##         Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
## &quot;2020-01-02&quot; &quot;2020-02-08&quot; &quot;2020-03-16&quot; &quot;2020-03-16&quot; &quot;2020-04-24&quot; &quot;2020-05-31&quot;</code></pre>
<pre><code>## Confirming months plotted: date</code></pre>
<pre><code>## 
##  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec 
## 5472 5424 5760 5760 5952  432    0    0    0    0    0    0</code></pre>
<pre><code>## png 
##   2</code></pre>
<pre><code>## png 
##   2</code></pre>
<pre><code>## png 
##   2</code></pre>
<p>Figure <a href="#fig:timeVariationGWhNormalised">3.8</a> is a similar plot but in this case the generation is normalised within each period to enable clarification of changes in the temporal <em>shape</em> of demand rather than changes in the overall level. As we can see the normalised plots indicate that the relative temporal distribution of generation (demand) is very similar between each period. The shape of demand is therefore relatively unchanged, but it's level is distinctly lower (Figure <a href="#fig:timeVariationGWh">3.7</a>).</p>
<pre><code>## Warning in checkPrep(mydata, vars, type, remove.calm = FALSE): Detected data with Daylight Saving
## Time, converting to UTC/GMT</code></pre>
<div class="figure"><span id="fig:timeVariationGWhNormalised"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/timeVariationGWhNormalised-1.png" alt="timeVariation plots for normalised half-hourly GW generation comparing pre/lockdown 2020 with the same months in previous years starting in 2018" width="672" />
<p class="caption">
Figure 3.8: timeVariation plots for normalised half-hourly GW generation comparing pre/lockdown 2020 with the same months in previous years starting in 2018
</p>
</div>
</div>
<div id="daily-patterns" class="section level3">
<h3><span class="header-section-number">3.1.3</span> Daily patterns</h3>
<p>For this analysis we have shifted the dates for the comparison years to ensure that weekdays and weekends align in each year of data but this does <strong>not</strong> mean that Easter is the same weekend across the comparison periods nor that Bank Holidays (e.g. VE day 2020) are consistent.</p>
<p>Figure <a href="#fig:compareDailyGWhPlot">3.9</a> shows the most recent mean daily half-hourly GW compared to the same day in previous years. As hinted by Figure <a href="#fig:timeVariationGWh">3.7</a>, lockdown clearly reduced demand below the seasonal trend as Figure <a href="#fig:TheilSenGWhPlot">3.1</a> suggested and also levels of demand are now starting to converge on the seasonal trend (c.f. Figure <a href="#fig:timeVariationGWh">3.7</a>).</p>
<blockquote>
<p>Beware temperature differences - need to control for heating degree days as 2020 was a <em>very</em> warm spring</p>
</blockquote>
<pre><code>## Warning: Ignoring unknown parameters: yMin, yMax</code></pre>
<pre><code>## Saving 9 x 5 in image</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;
## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:compareDailyGWhPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyGWhPlot-1.png" alt="Comparative daily mean half-hour generation levels 2020 vs pre-2020" width="672" />
<p class="caption">
Figure 3.9: Comparative daily mean half-hour generation levels 2020 vs pre-2020
</p>
</div>
<p>Figure <a href="#fig:compareDailyGWhpcPlot"><strong>??</strong></a> shows the percentage difference between the mean half-hourly generation per day in 2020 and the pre 2020 average for the same day. As we can see January 2020 was already slightly lower than previous years but February appears similar. There appears to be a substantial lockdown effect albiet with some fluctuations and very large dips on VE Day (Friday 8th May) and Thursday 28th May.</p>
<div class="figure"><span id="fig:compareDailyGWhpcPlot1"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyGWhpcPlot-1.png" alt="Percentage difference in mean generation levels 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.10: Percentage difference in mean generation levels 2020 vs pre 2020
</p>
</div>
<pre><code>## Warning: Ignoring unknown parameters: yMin, yMax</code></pre>
<pre><code>## Saving 9 x 5 in image</code></pre>
<div class="figure"><span id="fig:compareDailyGWhpcPlot2"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyGWhpcPlot-2.png" alt="Percentage difference in mean generation levels 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.11: Percentage difference in mean generation levels 2020 vs pre 2020
</p>
</div>
<p>Figure <a href="#fig:peakyTest">3.12</a> shows the trend in the ratio between maximum and minimum half-hourly generation by day. This shows that 2020 was already less 'peaky' than previous years with a lower ratio between maximum and minimum generation on most days. This appear to have amplified in the first week or so of UK lockdown with a further reduction in the ratio but this has not been sustained over time with greater variance as we move into May 2020.</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:peakyTest"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/peakyTest-1.png" alt="Ratio of maximum to minimum generation per day" width="672" />
<p class="caption">
Figure 3.12: Ratio of maximum to minimum generation per day
</p>
</div>
</div>
<div id="weekly-patterns" class="section level3">
<h3><span class="header-section-number">3.1.4</span> Weekly patterns</h3>
<p>tbc</p>
</div>
</div>
<div id="carbon-intensity-analysing-deviation-from-normal" class="section level2">
<h2><span class="header-section-number">3.2</span> Carbon Intensity: Analysing deviation from 'normal'</h2>
<p>There are two aspects to this. The first is <code>carbon intensity</code> which is driven by the mix of fuels being used to generate electricity at any given time. The second is the total greenhouse gasses emitted which is, obviously, the intensity * the volume. Given the slight uncertainty over units (see Section <a href="#data">2</a>) we assume this is <code>GENERATION</code> * <code>CARBON_INTENSITY</code>.</p>
<p>Clearly the first of these is driven by the mix of fuels and in the UK this reflects a complex dynamic system of availability of renewables, price, interconnect and demand. To some extent we would expect that lower overall demand should (but not <a href="https://www.nationalgrideso.com/news/our-electricity-greener-lockdown">always</a>) increase the share of renewables. However other factors are also at play:</p>
<ul>
<li>some electricity-usage practices may have shifted to (or indeed away from) periods which are likely to have high renewable availability;</li>
<li>some electricity-usage practices may have shifted away from the 'usual' morning and evening peak periods which are traditionally thought to require carbon intense peaking generation if sufficient pumped hydro is not available;</li>
<li>low periods of demand might <a href="https://www.nationalgrideso.com/news/our-electricity-greener-lockdown">require system services</a> from higher carbon generation</li>
</ul>
<div id="overall-trends-1" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Overall trends</h3>
<p>Figure <a href="#fig:TheilSenCIPlot">3.13</a> agin uses the openair <code>TheilSen()</code> function <span class="citation">(Carslaw and Ropkins 2012)</span> to create a de-seasoned trend plot but this time for mean half-hourly carbon intensity by peak demand period. Again Table <a href="#tab:TheilSenCIPlot">3.3</a> indicates the years over which the trend is calculated. This plot shows that carbon intensity has fallen by around 40 kg CO2e/MWh per year over the time period in all time periods. However it is also noticeable that mean carbon intensity has marginally increased above trend in the months of lockdown.</p>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:TheilSenCIPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/TheilSenCIPlot-1.png" alt="Theil-Sen plot of mean half-hourly carbon intensity per month since 2016-01-01" width="672" />
<p class="caption">
Figure 3.13: Theil-Sen plot of mean half-hourly carbon intensity per month since 2016-01-01
</p>
</div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:TheilSenCIPlot">Table 3.3: </span>Mean half-hourly carbon intensity (kg CO2e/kWh) by year and peak period - 2020 incomplete
</caption>
<thead>
<tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:right;">
Early morning
</th>
<th style="text-align:right;">
Morning peak
</th>
<th style="text-align:right;">
Day time
</th>
<th style="text-align:right;">
Evening peak
</th>
<th style="text-align:right;">
Late evening
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2016
</td>
<td style="text-align:right;">
278.60
</td>
<td style="text-align:right;">
312.74
</td>
<td style="text-align:right;">
298.33
</td>
<td style="text-align:right;">
329.41
</td>
<td style="text-align:right;">
302.58
</td>
</tr>
<tr>
<td style="text-align:right;">
2017
</td>
<td style="text-align:right;">
243.25
</td>
<td style="text-align:right;">
274.27
</td>
<td style="text-align:right;">
262.10
</td>
<td style="text-align:right;">
290.48
</td>
<td style="text-align:right;">
266.75
</td>
</tr>
<tr>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
209.85
</td>
<td style="text-align:right;">
247.76
</td>
<td style="text-align:right;">
237.40
</td>
<td style="text-align:right;">
268.98
</td>
<td style="text-align:right;">
234.81
</td>
</tr>
<tr>
<td style="text-align:right;">
2019
</td>
<td style="text-align:right;">
190.82
</td>
<td style="text-align:right;">
227.35
</td>
<td style="text-align:right;">
217.68
</td>
<td style="text-align:right;">
241.88
</td>
<td style="text-align:right;">
215.66
</td>
</tr>
<tr>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
166.23
</td>
<td style="text-align:right;">
192.91
</td>
<td style="text-align:right;">
180.57
</td>
<td style="text-align:right;">
212.99
</td>
<td style="text-align:right;">
189.66
</td>
</tr>
</tbody>
</table>
<pre><code>## png 
##   2</code></pre>
<p>Use the openair results object to estimate what the 2020 values would have been if the deaseasoned trend slope had continued.</p>
<pre><code>## Saving 7 x 5 in image</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:calculateCIDiffFromTrend">Table 3.4: </span>GWh above/below expected mean half-hourly CI by month
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
diff_Early morning
</th>
<th style="text-align:right;">
diff_Morning peak
</th>
<th style="text-align:right;">
diff_Day time
</th>
<th style="text-align:right;">
diff_Evening peak
</th>
<th style="text-align:right;">
diff_Late evening
</th>
<th style="text-align:right;">
diffTotal
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
2.56
</td>
<td style="text-align:right;">
5.32
</td>
<td style="text-align:right;">
-2.88
</td>
<td style="text-align:right;">
-12.10
</td>
<td style="text-align:right;">
-8.62
</td>
<td style="text-align:right;">
-15.72
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-27.81
</td>
<td style="text-align:right;">
-31.06
</td>
<td style="text-align:right;">
-49.18
</td>
<td style="text-align:right;">
-34.72
</td>
<td style="text-align:right;">
-28.76
</td>
<td style="text-align:right;">
-171.53
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
1.35
</td>
<td style="text-align:right;">
11.18
</td>
<td style="text-align:right;">
9.43
</td>
<td style="text-align:right;">
-6.02
</td>
<td style="text-align:right;">
-3.68
</td>
<td style="text-align:right;">
12.25
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
17.17
</td>
<td style="text-align:right;">
7.27
</td>
<td style="text-align:right;">
-0.75
</td>
<td style="text-align:right;">
13.08
</td>
<td style="text-align:right;">
17.17
</td>
<td style="text-align:right;">
53.93
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
15.21
</td>
<td style="text-align:right;">
6.02
</td>
<td style="text-align:right;">
1.45
</td>
<td style="text-align:right;">
15.84
</td>
<td style="text-align:right;">
18.46
</td>
<td style="text-align:right;">
56.98
</td>
</tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:calculateCIDiffFromTrend">Table 3.4: </span>% above/below expected mean half-hourly CI by month
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
pcDiff_Early morning
</th>
<th style="text-align:right;">
pcDiff_Morning peak
</th>
<th style="text-align:right;">
pcDiff_Day time
</th>
<th style="text-align:right;">
pcDiff_Evening peak
</th>
<th style="text-align:right;">
pcDiff_Late evening
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
1.56
</td>
<td style="text-align:right;">
2.72
</td>
<td style="text-align:right;">
-1.51
</td>
<td style="text-align:right;">
-5.60
</td>
<td style="text-align:right;">
-4.54
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-17.20
</td>
<td style="text-align:right;">
-16.10
</td>
<td style="text-align:right;">
-26.22
</td>
<td style="text-align:right;">
-16.28
</td>
<td style="text-align:right;">
-15.36
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
5.87
</td>
<td style="text-align:right;">
5.09
</td>
<td style="text-align:right;">
-2.85
</td>
<td style="text-align:right;">
-1.99
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
10.96
</td>
<td style="text-align:right;">
3.87
</td>
<td style="text-align:right;">
-0.41
</td>
<td style="text-align:right;">
6.28
</td>
<td style="text-align:right;">
9.42
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
9.87
</td>
<td style="text-align:right;">
3.25
</td>
<td style="text-align:right;">
0.81
</td>
<td style="text-align:right;">
7.70
</td>
<td style="text-align:right;">
10.27
</td>
</tr>
</tbody>
</table>
<p>Theil-Sen by weekday (for fun):</p>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<p><img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/theilSenCIDoWPlot-1.png" width="672" /></p>
</div>
<div id="half-hourly-patterns-1" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Half-hourly patterns</h3>
<p>Figure <a href="#fig:recentDateTimeCIPlot">3.14</a> shows half-hourly carbon intensity since 2020-02-01. Overall generation has fallen as we would expect given the season (less heating and lighting required) and weekdays are indeed less easy to distinguish from weekends.</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:recentDateTimeCIPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/recentDateTimeCIPlot-1.png" alt="Half-hourly CO2e emissions, UK (recent)" width="672" />
<p class="caption">
Figure 3.14: Half-hourly CO2e emissions, UK (recent)
</p>
</div>
<p>Figure <a href="#fig:recentHalfHourlyProfileCIPlot">3.15</a> shows the daily carbon intensity profiles over time for each day of the week.</p>
<div class="figure"><span id="fig:recentHalfHourlyProfileCIPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/recentHalfHourlyProfileCIPlot-1.png" alt="Half-hourly generation, UK (recent)" width="672" />
<p class="caption">
Figure 3.15: Half-hourly generation, UK (recent)
</p>
</div>
<p>Figure <a href="#fig:makeWeekDayCIPlot">3.16</a> shows the mean half-hourly CO2e per day. Need to bear in mind the trends identified above.</p>
<pre><code>## Saving 9 x 5 in image</code></pre>
<div class="figure"><span id="fig:makeWeekDayCIPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/makeWeekDayCIPlot-1.png" alt="half-hourly CI" width="672" />
<p class="caption">
Figure 3.16: half-hourly CI
</p>
</div>
<p>Figure <a href="#fig:makeWeekdayTimeCIplot">3.17</a> shows the mean half-hourly CO2e per half-hour of each day. This plot shows the values as a proportion of the sum of the means across all half hours of each day to illustrate the relative, rather than absolute, shift in generation.</p>
<pre><code>## Saving 9 x 5 in image</code></pre>
<div class="figure"><span id="fig:makeWeekdayTimeCIplot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/makeWeekdayTimeCIplot-1.png" alt="% half-hourly CI" width="672" />
<p class="caption">
Figure 3.17: % half-hourly CI
</p>
</div>
<p>Figure <a href="#fig:timeVariationCI">3.18</a> shows the difference between hourly and weekday patterns for lockdown 2020 and the previous year(s) starting from January 2018. This plot is not particularly informative since we now CI is already lower in 2020 than previous years and we would expect it to fall during the spring as solar generation increases its contributon. The lockdown phases will also be affected by small numbers of highly windy days.</p>
<pre><code>## Warning in checkPrep(mydata, vars, type, remove.calm = FALSE): Detected data with Daylight Saving
## Time, converting to UTC/GMT</code></pre>
<div class="figure"><span id="fig:timeVariationCI"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/timeVariationCI-1.png" alt="timeVariation plots for half-hourly carbon intensity comparing lockdown 2020 up to 2020-06-01" width="672" />
<p class="caption">
Figure 3.18: timeVariation plots for half-hourly carbon intensity comparing lockdown 2020 up to 2020-06-01
</p>
</div>
<pre><code>## Confirming dates plotted: date (as set for openair)</code></pre>
<pre><code>##                  Min.               1st Qu.                Median                  Mean 
## &quot;2017-01-05 00:00:00&quot; &quot;2017-11-11 17:37:30&quot; &quot;2018-09-18 12:15:00&quot; &quot;2018-09-18 10:56:48&quot; 
##               3rd Qu.                  Max. 
## &quot;2019-07-26 05:52:30&quot; &quot;2020-05-31 23:30:00&quot;</code></pre>
<pre><code>## Confirming dates plotted: dateFixed</code></pre>
<pre><code>##         Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
## &quot;2020-01-02&quot; &quot;2020-02-08&quot; &quot;2020-03-16&quot; &quot;2020-03-16&quot; &quot;2020-04-24&quot; &quot;2020-05-31&quot;</code></pre>
<pre><code>## Confirming months plotted: date</code></pre>
<pre><code>## 
##  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec 
## 5472 5424 5760 5760 5952  432    0    0    0    0    0    0</code></pre>
<pre><code>## png 
##   2</code></pre>
<pre><code>## png 
##   2</code></pre>
<pre><code>## png 
##   2</code></pre>
</div>
<div id="daily-patterns-1" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Daily patterns</h3>
<p>Figure <a href="#fig:compareDailyCIPlot"><strong>??</strong></a> shows the mean half-hourly carbon intensity per day in 2020 and the pre 2020 average for the same day. As we would expect given Figure <a href="#fig:TheilSenCIPlot">3.13</a>, 2020 was already considerably lower than the average of previous years but this is not necessarily sustained through lockdown although the affects of weather on solar and wind availability need to be taken in to account.</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:compareDailyCIPlot1"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyCIPlot-1.png" alt="Percentage difference in mean carbon intensity levels 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.19: Percentage difference in mean carbon intensity levels 2020 vs pre 2020
</p>
</div>
<pre><code>## Warning: Ignoring unknown parameters: yMin, yMax</code></pre>
<pre><code>## Saving 9 x 5 in image
## `geom_smooth()` using formula &#39;y ~ x&#39;
## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:compareDailyCIPlot2"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyCIPlot-2.png" alt="Percentage difference in mean carbon intensity levels 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.20: Percentage difference in mean carbon intensity levels 2020 vs pre 2020
</p>
</div>
<p>Figure <a href="#fig:compareDailyCIpcPlot"><strong>??</strong></a> shows the percentage difference between the mean half-hourly carbon intensity per day in 2020 and the pre 2020 average for the same day. As expected, 2020 was already considerably lower than the average of previous years but this is not necessarily sustained through lockdown although the affects of weather on solar and wind availability need to be taken in to account.</p>
<div class="figure"><span id="fig:compareDailyCIpcPlot1"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyCIpcPlot-1.png" alt="Percentage difference in mean carbon intensity levels 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.21: Percentage difference in mean carbon intensity levels 2020 vs pre 2020
</p>
</div>
<pre><code>## Warning: Ignoring unknown parameters: yMin, yMax</code></pre>
<pre><code>## Saving 9 x 5 in image</code></pre>
<div class="figure"><span id="fig:compareDailyCIpcPlot2"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyCIpcPlot-2.png" alt="Percentage difference in mean carbon intensity levels 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.22: Percentage difference in mean carbon intensity levels 2020 vs pre 2020
</p>
</div>
</div>
<div id="weekly-patterns-1" class="section level3">
<h3><span class="header-section-number">3.2.4</span> Weekly patterns</h3>
<p>tbc</p>
</div>
</div>
<div id="carbon-emissions-total-analysing-deviation-from-normal" class="section level2">
<h2><span class="header-section-number">3.3</span> Carbon emissions (total): Analysing deviation from 'normal'</h2>
<p>In this section we use our calculation of total CO2e emitted per half hour (see Section <a href="#genData">2.1</a>) to analyse the changes in total CO2e emitted which is, after all, what we are mostly interested in from a climate change point of view. Remember that this value is driven <em>both</em> by total generation (demand) <em>and</em> carbon intensity. As we saw above, these are not always tightly correlated.</p>
<div id="overall-trends-2" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Overall trends</h3>
<p>Figure <a href="#fig:TheilSenC02eTPlot">3.23</a> again uses the openair <code>TheilSen()</code> function <span class="citation">(Carslaw and Ropkins 2012)</span> to create a de-seasoned trend plot but this time for mean half-hourly carbon intensity by peak demnand period. Again Table <a href="#tab:TheilSenC02eTPlot">3.5</a> indicates the years over which the trend is calculated.</p>
<p>This plot shows that total CO2e emissions intensity has fallen by a half-hourly mean of ~600-800 tonnes of CO2e over the time period. However there is some variation around this trend with apparently slightly above trend emissions in the evening peak period during April and May 2020 noticeable despite the almost complete absence of coal generation during this period (see Annex, Figure <a href="#fig:fuelTrendPlots"><strong>??</strong></a>).</p>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<div class="figure"><span id="fig:TheilSenC02eTPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/TheilSenC02eTPlot-1.png" alt="Theil-Sen plot of mean half-hourly kg CO2e emissions per month since 2016-01-01" width="672" />
<p class="caption">
Figure 3.23: Theil-Sen plot of mean half-hourly kg CO2e emissions per month since 2016-01-01
</p>
</div>
<pre><code>## png 
##   2</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:TheilSenC02eTPlot">Table 3.5: </span>Mean half-hourly C02e (T) by year and peak period - 2020 incomplete
</caption>
<thead>
<tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:right;">
Early morning
</th>
<th style="text-align:right;">
Morning peak
</th>
<th style="text-align:right;">
Day time
</th>
<th style="text-align:right;">
Evening peak
</th>
<th style="text-align:right;">
Late evening
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2016
</td>
<td style="text-align:right;">
3899.12
</td>
<td style="text-align:right;">
5675.74
</td>
<td style="text-align:right;">
5872.71
</td>
<td style="text-align:right;">
6681.71
</td>
<td style="text-align:right;">
4947.00
</td>
</tr>
<tr>
<td style="text-align:right;">
2017
</td>
<td style="text-align:right;">
3397.01
</td>
<td style="text-align:right;">
4979.77
</td>
<td style="text-align:right;">
5190.13
</td>
<td style="text-align:right;">
5906.01
</td>
<td style="text-align:right;">
4374.40
</td>
</tr>
<tr>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
2908.24
</td>
<td style="text-align:right;">
4473.56
</td>
<td style="text-align:right;">
4664.84
</td>
<td style="text-align:right;">
5386.48
</td>
<td style="text-align:right;">
3793.76
</td>
</tr>
<tr>
<td style="text-align:right;">
2019
</td>
<td style="text-align:right;">
2579.97
</td>
<td style="text-align:right;">
4024.34
</td>
<td style="text-align:right;">
4184.74
</td>
<td style="text-align:right;">
4705.12
</td>
<td style="text-align:right;">
3412.42
</td>
</tr>
<tr>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
2179.26
</td>
<td style="text-align:right;">
3223.99
</td>
<td style="text-align:right;">
3355.45
</td>
<td style="text-align:right;">
4063.70
</td>
<td style="text-align:right;">
2948.73
</td>
</tr>
</tbody>
</table>
<p>Now use the openair results object to estimate what the 2020 values would have been if the deaseasoned trend slope had continued.</p>
<pre><code>## Saving 7 x 5 in image</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:calculateCO2DiffFromTrend">Table 3.6: </span>GWh above/below expected mean half-hourly CO2e (T) by month
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
diff_Early morning
</th>
<th style="text-align:right;">
diff_Morning peak
</th>
<th style="text-align:right;">
diff_Day time
</th>
<th style="text-align:right;">
diff_Evening peak
</th>
<th style="text-align:right;">
diff_Late evening
</th>
<th style="text-align:right;">
diffTotal
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
2.90
</td>
<td style="text-align:right;">
-88.67
</td>
<td style="text-align:right;">
-217.74
</td>
<td style="text-align:right;">
-527.16
</td>
<td style="text-align:right;">
-156.01
</td>
<td style="text-align:right;">
-986.69
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-548.43
</td>
<td style="text-align:right;">
-723.88
</td>
<td style="text-align:right;">
-1320.14
</td>
<td style="text-align:right;">
-1015.65
</td>
<td style="text-align:right;">
-718.42
</td>
<td style="text-align:right;">
-4326.53
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
-46.29
</td>
<td style="text-align:right;">
-94.17
</td>
<td style="text-align:right;">
130.34
</td>
<td style="text-align:right;">
-295.98
</td>
<td style="text-align:right;">
-184.65
</td>
<td style="text-align:right;">
-490.76
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
-21.77
</td>
<td style="text-align:right;">
-357.98
</td>
<td style="text-align:right;">
-319.24
</td>
<td style="text-align:right;">
55.27
</td>
<td style="text-align:right;">
120.12
</td>
<td style="text-align:right;">
-523.60
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
109.57
</td>
<td style="text-align:right;">
-169.92
</td>
<td style="text-align:right;">
-129.60
</td>
<td style="text-align:right;">
240.57
</td>
<td style="text-align:right;">
237.76
</td>
<td style="text-align:right;">
288.38
</td>
</tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:calculateCO2DiffFromTrend">Table 3.6: </span>% above/below expected mean half-hourly CO2e (T) by month
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:right;">
pcDiff_Early morning
</th>
<th style="text-align:right;">
pcDiff_Morning peak
</th>
<th style="text-align:right;">
pcDiff_Day time
</th>
<th style="text-align:right;">
pcDiff_Evening peak
</th>
<th style="text-align:right;">
pcDiff_Late evening
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan 2020
</td>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:right;">
-2.62
</td>
<td style="text-align:right;">
-6.06
</td>
<td style="text-align:right;">
-12.78
</td>
<td style="text-align:right;">
-5.36
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb 2020
</td>
<td style="text-align:right;">
-26.09
</td>
<td style="text-align:right;">
-21.71
</td>
<td style="text-align:right;">
-37.29
</td>
<td style="text-align:right;">
-24.99
</td>
<td style="text-align:right;">
-25.07
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar 2020
</td>
<td style="text-align:right;">
-2.24
</td>
<td style="text-align:right;">
-2.87
</td>
<td style="text-align:right;">
3.73
</td>
<td style="text-align:right;">
-7.39
</td>
<td style="text-align:right;">
-6.55
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr 2020
</td>
<td style="text-align:right;">
-1.08
</td>
<td style="text-align:right;">
-11.09
</td>
<td style="text-align:right;">
-9.28
</td>
<td style="text-align:right;">
1.40
</td>
<td style="text-align:right;">
4.33
</td>
</tr>
<tr>
<td style="text-align:left;">
May 2020
</td>
<td style="text-align:right;">
5.52
</td>
<td style="text-align:right;">
-5.35
</td>
<td style="text-align:right;">
-3.83
</td>
<td style="text-align:right;">
6.19
</td>
<td style="text-align:right;">
8.72
</td>
</tr>
</tbody>
</table>
<p>Theil-Sen by weekday (for fun):</p>
<pre><code>## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;
## [1] &quot;Taking bootstrap samples. Please wait.&quot;</code></pre>
<p><img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/theilSenCO2eDoWPlot-1.png" width="672" /></p>
</div>
<div id="half-hourly-patterns-2" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Half-hourly patterns</h3>
<p>Figure <a href="#fig:recentDateTimeC02ekgPlot">3.24</a> shows total half-hourly CO2e emissions since 2020-02-01. Overall generation has fallen as we would expect given the season (less heating and lighting required) and weekdays are indeed less easy to distinguish from weekends.</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:recentDateTimeC02ekgPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/recentDateTimeC02ekgPlot-1.png" alt="Half-hourly total CO2e emissions, UK (recent)" width="672" />
<p class="caption">
Figure 3.24: Half-hourly total CO2e emissions, UK (recent)
</p>
</div>
<p>Figure <a href="#fig:recentHalfHourlyProfileC02ekgPlot">3.25</a> shows the daily CO2e emissions profiles over time for each day of the week since 2020-02-01.</p>
<div class="figure"><span id="fig:recentHalfHourlyProfileC02ekgPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/recentHalfHourlyProfileC02ekgPlot-1.png" alt="Half-hourly CO2e emissions, UK (recent)" width="672" />
<p class="caption">
Figure 3.25: Half-hourly CO2e emissions, UK (recent)
</p>
</div>
<p>Figure <a href="#fig:makeWeekDayCO2eTPlot">3.26</a> shows the mean half-hourly CO2e per day. Need to bear in mind the trends identified above.</p>
<pre><code>## Saving 9 x 5 in image</code></pre>
<div class="figure"><span id="fig:makeWeekDayCO2eTPlot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/makeWeekDayCO2eTPlot-1.png" alt="half-hourly CO2e" width="672" />
<p class="caption">
Figure 3.26: half-hourly CO2e
</p>
</div>
<p>Figure <a href="#fig:makeWeekdayTimeCO2eTplot">3.27</a> shows the mean half-hourly CO2e per half-hour of each day. This plot shows the values as a proportion of the sum of the means across all half hours of each day to illustrate the relative, rather than absolute, shift in generation.</p>
<pre><code>## Saving 9 x 5 in image</code></pre>
<div class="figure"><span id="fig:makeWeekdayTimeCO2eTplot"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/makeWeekdayTimeCO2eTplot-1.png" alt="% half-hourly CO2e" width="672" />
<p class="caption">
Figure 3.27: % half-hourly CO2e
</p>
</div>
<p>Figure <a href="#fig:timeVariationCO2e">3.28</a> shows the difference between hourly and weekday patterns for lockdown 2020 and the previous year(s) starting from January 2018. Again, due to the downward trends we have already identified, we would expect total CO2e emissions to be lower during 2020 and also to fall during the spring as solar generation increases its contributon.</p>
<pre><code>## Warning in checkPrep(mydata, vars, type, remove.calm = FALSE): Detected data with Daylight Saving
## Time, converting to UTC/GMT</code></pre>
<div class="figure"><span id="fig:timeVariationCO2e"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/timeVariationCO2e-1.png" alt="timeVariation plots for half-hourly CO2e comparing lockdown 2020 with pre-lockdown starting in 2018" width="672" />
<p class="caption">
Figure 3.28: timeVariation plots for half-hourly CO2e comparing lockdown 2020 with pre-lockdown starting in 2018
</p>
</div>
<pre><code>## Confirming dates plotted: date (as set for openair)</code></pre>
<pre><code>##                  Min.               1st Qu.                Median                  Mean 
## &quot;2017-01-05 00:00:00&quot; &quot;2017-11-11 17:37:30&quot; &quot;2018-09-18 12:15:00&quot; &quot;2018-09-18 10:56:48&quot; 
##               3rd Qu.                  Max. 
## &quot;2019-07-26 05:52:30&quot; &quot;2020-05-31 23:30:00&quot;</code></pre>
<pre><code>## Confirming dates plotted: dateFixed</code></pre>
<pre><code>##         Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
## &quot;2020-01-02&quot; &quot;2020-02-08&quot; &quot;2020-03-16&quot; &quot;2020-03-16&quot; &quot;2020-04-24&quot; &quot;2020-05-31&quot;</code></pre>
<pre><code>## Confirming months plotted: date</code></pre>
<pre><code>## 
##  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec 
## 5472 5424 5760 5760 5952  432    0    0    0    0    0    0</code></pre>
<pre><code>## png 
##   2</code></pre>
<pre><code>## png 
##   2</code></pre>
<pre><code>## png 
##   2</code></pre>
</div>
<div id="daily-patterns-2" class="section level3">
<h3><span class="header-section-number">3.3.3</span> Daily patterns</h3>
<p>Figure <a href="#fig:compareDailyCO2ekgPlot"><strong>??</strong></a> shows the mean half-hourly carbon intensity per day in 2020 and the pre 2020 average for the same day. As expected, 2020 was already considerably lower than the average of previous years but this is not necessarily sustained through lockdown although the affects of weather on solar and wind availability need to be taken in to account.</p>
<blockquote>
<p>check y axis</p>
</blockquote>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:compareDailyCO2ekgPlot1"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyCO2ekgPlot-1.png" alt="Mean half-hourly total CO2e by day, 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.29: Mean half-hourly total CO2e by day, 2020 vs pre 2020
</p>
</div>
<pre><code>## Warning: Ignoring unknown parameters: yMin, yMax</code></pre>
<pre><code>## Saving 9 x 5 in image
## `geom_smooth()` using formula &#39;y ~ x&#39;
## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:compareDailyCO2ekgPlot2"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyCO2ekgPlot-2.png" alt="Mean half-hourly total CO2e by day, 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.30: Mean half-hourly total CO2e by day, 2020 vs pre 2020
</p>
</div>
<p>Figure <a href="#fig:compareDailyC02ekgpcPlot"><strong>??</strong></a> shows the percentage difference between the mean half-hourly carbon intensity per day in 2020 and the pre 2020 average for the same day. As expected, 2020 was already considerably lower than the average of previous years but this is not necessarily sustained through lockdown although the affects of weather on solar and wind availability need to be taken in to account.</p>
<div class="figure"><span id="fig:compareDailyC02ekgpcPlot1"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyC02ekgpcPlot-1.png" alt="Percentage difference in mean half-hourly CO2e 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.31: Percentage difference in mean half-hourly CO2e 2020 vs pre 2020
</p>
</div>
<pre><code>## Warning: Ignoring unknown parameters: yMin, yMax</code></pre>
<pre><code>## Saving 9 x 5 in image</code></pre>
<div class="figure"><span id="fig:compareDailyC02ekgpcPlot2"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/compareDailyC02ekgpcPlot-2.png" alt="Percentage difference in mean half-hourly CO2e 2020 vs pre 2020" width="672" />
<p class="caption">
Figure 3.32: Percentage difference in mean half-hourly CO2e 2020 vs pre 2020
</p>
</div>
</div>
<div id="weekly-patterns-2" class="section level3">
<h3><span class="header-section-number">3.3.4</span> Weekly patterns</h3>
<p>tbc</p>
</div>
</div>
</div>
<div id="summary-to-date" class="section level1">
<h1><span class="header-section-number">4</span> Summary (to date)</h1>
</div>
<div id="about" class="section level1">
<h1><span class="header-section-number">5</span> About</h1>
<div id="citation" class="section level2">
<h2><span class="header-section-number">5.1</span> Citation</h2>
<p>If you wish to use any of the material from this report please cite as:</p>
<ul>
<li>Ben Anderson (2020) <em>UK Electricity Generation and Carbon Itensity: covid 19 lockdown v1.0</em>, University of Southampton: Sustainable Energy Research Centre.</li>
</ul>
<p>This work is (c) 2020 the authors. Usage rights are specified in the License section (<a href="#license">5.4</a>).</p>
</div>
<div id="report-circulation" class="section level2">
<h2><span class="header-section-number">5.2</span> Report circulation</h2>
<ul>
<li>Public – this report is intended for publication.</li>
</ul>
</div>
<div id="code" class="section level2">
<h2><span class="header-section-number">5.3</span> Code</h2>
<p>All code used to create this report is available from:</p>
<ul>
<li><a href="https://github.com/CfSOtago/gridCarbon" class="uri">https://github.com/CfSOtago/gridCarbon</a></li>
</ul>
</div>
<div id="license" class="section level2">
<h2><span class="header-section-number">5.4</span> License</h2>
<p>This work is made available under the Creative Commons <a href="https://creativecommons.org/licenses/by-sa/4.0/">Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) License</a>.</p>
<p>This means you are free to:</p>
<ul>
<li><em>Share</em> — copy and redistribute the material in any medium or format</li>
<li><em>Adapt</em> — remix, transform, and build upon the material for any purpose, even commercially.</li>
</ul>
<p>Under the following terms:</p>
<ul>
<li><em>Attribution</em> — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.</li>
<li><em>ShareAlike</em> — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.</li>
<li><em>No additional restrictions</em> — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.</li>
</ul>
<p><strong>Notices:</strong></p>
<ul>
<li>You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.</li>
<li>No warranties are given. The license may not give you all of the permissions necessary for your intended use. For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.</li>
</ul>
<p>For the avoidance of doubt and explanation of terms please refer to the full <a href="https://creativecommons.org/licenses/by-sa/4.0/">license notice</a> and <a href="https://creativecommons.org/licenses/by-sa/4.0/legalcode">legal code</a>.</p>
</div>
<div id="history" class="section level2">
<h2><span class="header-section-number">5.5</span> History</h2>
<p>You may not be reading the most recent version of this report. Please check:</p>
<ul>
<li>the github <a href="https://github.com/CfSOtago/gridCarbon">R code repository</a>;</li>
<li>our <a href="https://github.com/CfSOtago/gridCarbon/issues">issues list</a> for any unfixed problems;</li>
<li>our <a href="https://cfsotago.github.io/gridCarbon/">project publictions</a>;</li>
</ul>
<p>We do not 'support' the code but if you notice a problem please check the <a href="https://github.com/CfSOtago/gridCarbon/issues">issues</a> on our <a href="https://github.com/CfSOtago/gridCarbon">repo</a> and if it doesn't already exist, please open a new one. * this <a href="https://github.com/CfSOtago/gridCarbon/commits/master/dataAnalysis/">report's edit history</a></p>
</div>
<div id="support" class="section level2">
<h2><span class="header-section-number">5.6</span> Support</h2>
<p>This work was supported by:</p>
<ul>
<li>The <a href="https://www.otago.ac.nz/">University of Otago</a>;</li>
<li><a href="http://www.energy.soton.ac.uk/tag/spatialec/">SPATIALEC</a> - a <a href="http://ec.europa.eu/research/mariecurieactions/about-msca/actions/if/index_en.htm">Marie Skłodowska-Curie Global Fellowship</a> based at the University of Otago’s <a href="http://www.otago.ac.nz/centre-sustainability/staff/otago673896.html">Centre for Sustainability</a> (2017-2019) &amp; the University of Southampton's Sustainable Energy Research Group (2019-2020).</li>
<li>The European Union via <a href="http://www.energy.soton.ac.uk/tag/spatialec/">SPATIALEC</a>, a Marie Skłodowska-Curie <a href="https://ec.europa.eu/research/mariecurieactions/actions/individual-fellowships_en">Global Fellowship</a> based at the University of Otago’s <a href="http://www.otago.ac.nz/centre-sustainability/staff/otago673896.html">Centre for Sustainability</a> (2017-2019) &amp; the University of Southampton’s <a href="http://www.otago.ac.nz/centre-sustainability/staff/otago673896.html">Sustainable Energy Research Group</a> (2019-2020) (Anderson)</li>
</ul>

</div>
</div>
<div id="annexes" class="section level1">
<h1><span class="header-section-number">6</span> Annexes</h1>
<div id="grid-generation-data" class="section level2">
<h2><span class="header-section-number">6.1</span> Grid generation data</h2>
<table style="width: auto;" class="table table-condensed">
<caption>
<span id="tab:skimGrid">Table 6.1: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
gridGenDT
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
77184
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Date
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
difftime
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
factor
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
41
</td>
</tr>
<tr>
<td style="text-align:left;">
POSIXct
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
DATETIME
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
77184
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
rDateTime
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
77184
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: Date</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
<th style="text-align:left;">
median
</th>
<th style="text-align:right;">
n_unique
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
obsDate
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
2016-01-01
</td>
<td style="text-align:left;">
2020-05-31
</td>
<td style="text-align:left;">
2018-03-16
</td>
<td style="text-align:right;">
1608
</td>
</tr>
<tr>
<td style="text-align:left;">
date
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
2016-01-01
</td>
<td style="text-align:left;">
2020-05-31
</td>
<td style="text-align:left;">
2018-03-16
</td>
<td style="text-align:right;">
1613
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: difftime</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
<th style="text-align:left;">
median
</th>
<th style="text-align:right;">
n_unique
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
hms
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
0 secs
</td>
<td style="text-align:left;">
84600 secs
</td>
<td style="text-align:left;">
42300 secs
</td>
<td style="text-align:right;">
48
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
ordered
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:left;">
top_counts
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
peakPeriod
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
FALSE
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Day: 24120, Ear: 22512, Eve: 12864, Lat: 12864
</td>
</tr>
<tr>
<td style="text-align:left;">
dow
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
TRUE
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
Fri: 11088, Sat: 11088, Mon: 11040, Tue: 11040
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
GAS
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.321635e+04
</td>
<td style="text-align:right;">
5.262500e+03
</td>
<td style="text-align:right;">
2291.00
</td>
<td style="text-align:right;">
9.161750e+03
</td>
<td style="text-align:right;">
1.297900e+04
</td>
<td style="text-align:right;">
1.717800e+04
</td>
<td style="text-align:right;">
2.747200e+04
</td>
<td style="text-align:left;">
▃▇▇▅▁
</td>
</tr>
<tr>
<td style="text-align:left;">
COAL
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.889460e+03
</td>
<td style="text-align:right;">
2.387990e+03
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
2.420000e+02
</td>
<td style="text-align:right;">
9.070000e+02
</td>
<td style="text-align:right;">
2.629000e+03
</td>
<td style="text-align:right;">
1.472400e+04
</td>
<td style="text-align:left;">
▇▂▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
NUCLEAR
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
6.871770e+03
</td>
<td style="text-align:right;">
9.980600e+02
</td>
<td style="text-align:right;">
3705.00
</td>
<td style="text-align:right;">
6.233000e+03
</td>
<td style="text-align:right;">
6.958000e+03
</td>
<td style="text-align:right;">
7.658000e+03
</td>
<td style="text-align:right;">
8.859000e+03
</td>
<td style="text-align:left;">
▁▂▆▇▃
</td>
</tr>
<tr>
<td style="text-align:left;">
WIND
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5.320740e+03
</td>
<td style="text-align:right;">
3.698880e+03
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
2.312000e+03
</td>
<td style="text-align:right;">
4.560000e+03
</td>
<td style="text-align:right;">
7.636000e+03
</td>
<td style="text-align:right;">
1.712900e+04
</td>
<td style="text-align:left;">
▇▆▃▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
HYDRO
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.165900e+02
</td>
<td style="text-align:right;">
2.544400e+02
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
2.090000e+02
</td>
<td style="text-align:right;">
3.830000e+02
</td>
<td style="text-align:right;">
5.870000e+02
</td>
<td style="text-align:right;">
1.403000e+03
</td>
<td style="text-align:left;">
▇▇▅▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
IMPORTS
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.529840e+03
</td>
<td style="text-align:right;">
9.561700e+02
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1.958000e+03
</td>
<td style="text-align:right;">
2.719000e+03
</td>
<td style="text-align:right;">
3.122000e+03
</td>
<td style="text-align:right;">
4.884000e+03
</td>
<td style="text-align:left;">
▂▅▇▇▂
</td>
</tr>
<tr>
<td style="text-align:left;">
BIOMASS
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.119890e+03
</td>
<td style="text-align:right;">
1.054840e+03
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
1.273000e+03
</td>
<td style="text-align:right;">
2.061000e+03
</td>
<td style="text-align:right;">
3.204000e+03
</td>
<td style="text-align:left;">
▇▂▃▅▂
</td>
</tr>
<tr>
<td style="text-align:left;">
OTHER
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7.356000e+02
</td>
<td style="text-align:right;">
8.244900e+02
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
8.800000e+01
</td>
<td style="text-align:right;">
1.420000e+02
</td>
<td style="text-align:right;">
1.466000e+03
</td>
<td style="text-align:right;">
2.173000e+03
</td>
<td style="text-align:left;">
▇▁▁▂▃
</td>
</tr>
<tr>
<td style="text-align:left;">
SOLAR
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.298800e+03
</td>
<td style="text-align:right;">
2.013820e+03
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
1.200000e+01
</td>
<td style="text-align:right;">
2.100000e+03
</td>
<td style="text-align:right;">
9.680000e+03
</td>
<td style="text-align:left;">
▇▂▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
STORAGE
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.648800e+02
</td>
<td style="text-align:right;">
3.280400e+02
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
1.740000e+02
</td>
<td style="text-align:right;">
3.920000e+02
</td>
<td style="text-align:right;">
2.394000e+03
</td>
<td style="text-align:left;">
▇▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
GENERATION
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.366393e+04
</td>
<td style="text-align:right;">
7.033020e+03
</td>
<td style="text-align:right;">
18287.00
</td>
<td style="text-align:right;">
2.826400e+04
</td>
<td style="text-align:right;">
3.346200e+04
</td>
<td style="text-align:right;">
3.858925e+04
</td>
<td style="text-align:right;">
5.342700e+04
</td>
<td style="text-align:left;">
▃▇▇▅▁
</td>
</tr>
<tr>
<td style="text-align:left;">
CARBON_INTENSITY
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.463800e+02
</td>
<td style="text-align:right;">
7.529000e+01
</td>
<td style="text-align:right;">
54.00
</td>
<td style="text-align:right;">
1.960000e+02
</td>
<td style="text-align:right;">
2.410000e+02
</td>
<td style="text-align:right;">
2.920000e+02
</td>
<td style="text-align:right;">
5.110000e+02
</td>
<td style="text-align:left;">
▂▇▇▃▁
</td>
</tr>
<tr>
<td style="text-align:left;">
LOW_CARBON
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.502779e+04
</td>
<td style="text-align:right;">
4.152490e+03
</td>
<td style="text-align:right;">
6755.00
</td>
<td style="text-align:right;">
1.182700e+04
</td>
<td style="text-align:right;">
1.450600e+04
</td>
<td style="text-align:right;">
1.781400e+04
</td>
<td style="text-align:right;">
3.074600e+04
</td>
<td style="text-align:left;">
▅▇▅▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
ZERO_CARBON
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.390791e+04
</td>
<td style="text-align:right;">
3.836820e+03
</td>
<td style="text-align:right;">
5164.00
</td>
<td style="text-align:right;">
1.088600e+04
</td>
<td style="text-align:right;">
1.352400e+04
</td>
<td style="text-align:right;">
1.654900e+04
</td>
<td style="text-align:right;">
2.847300e+04
</td>
<td style="text-align:left;">
▃▇▆▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
RENEWABLE
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7.036140e+03
</td>
<td style="text-align:right;">
4.045220e+03
</td>
<td style="text-align:right;">
125.00
</td>
<td style="text-align:right;">
3.826000e+03
</td>
<td style="text-align:right;">
6.496500e+03
</td>
<td style="text-align:right;">
9.708000e+03
</td>
<td style="text-align:right;">
2.311800e+04
</td>
<td style="text-align:left;">
▇▇▅▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
FOSSIL
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.510581e+04
</td>
<td style="text-align:right;">
6.712880e+03
</td>
<td style="text-align:right;">
2421.00
</td>
<td style="text-align:right;">
9.993750e+03
</td>
<td style="text-align:right;">
1.435500e+04
</td>
<td style="text-align:right;">
1.929900e+04
</td>
<td style="text-align:right;">
3.684200e+04
</td>
<td style="text-align:left;">
▅▇▆▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
GAS_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.842000e+01
</td>
<td style="text-align:right;">
1.088000e+01
</td>
<td style="text-align:right;">
6.60
</td>
<td style="text-align:right;">
3.100000e+01
</td>
<td style="text-align:right;">
4.000000e+01
</td>
<td style="text-align:right;">
4.680000e+01
</td>
<td style="text-align:right;">
6.530000e+01
</td>
<td style="text-align:left;">
▁▃▇▇▁
</td>
</tr>
<tr>
<td style="text-align:left;">
COAL_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.980000e+00
</td>
<td style="text-align:right;">
5.640000e+00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
9.000000e-01
</td>
<td style="text-align:right;">
2.900000e+00
</td>
<td style="text-align:right;">
7.200000e+00
</td>
<td style="text-align:right;">
3.020000e+01
</td>
<td style="text-align:left;">
▇▂▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
NUCLEAR_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.132000e+01
</td>
<td style="text-align:right;">
5.530000e+00
</td>
<td style="text-align:right;">
9.70
</td>
<td style="text-align:right;">
1.720000e+01
</td>
<td style="text-align:right;">
2.050000e+01
</td>
<td style="text-align:right;">
2.460000e+01
</td>
<td style="text-align:right;">
4.310000e+01
</td>
<td style="text-align:left;">
▃▇▅▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
WIND_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.617000e+01
</td>
<td style="text-align:right;">
1.136000e+01
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
7.000000e+00
</td>
<td style="text-align:right;">
1.380000e+01
</td>
<td style="text-align:right;">
2.290000e+01
</td>
<td style="text-align:right;">
5.830000e+01
</td>
<td style="text-align:left;">
▇▆▃▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
HYDRO_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.210000e+00
</td>
<td style="text-align:right;">
6.700000e-01
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
7.000000e-01
</td>
<td style="text-align:right;">
1.100000e+00
</td>
<td style="text-align:right;">
1.700000e+00
</td>
<td style="text-align:right;">
4.200000e+00
</td>
<td style="text-align:left;">
▇▇▅▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
IMPORTS_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7.870000e+00
</td>
<td style="text-align:right;">
3.310000e+00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
5.700000e+00
</td>
<td style="text-align:right;">
8.100000e+00
</td>
<td style="text-align:right;">
1.030000e+01
</td>
<td style="text-align:right;">
1.890000e+01
</td>
<td style="text-align:left;">
▂▆▇▃▁
</td>
</tr>
<tr>
<td style="text-align:left;">
BIOMASS_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.440000e+00
</td>
<td style="text-align:right;">
3.320000e+00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
3.700000e+00
</td>
<td style="text-align:right;">
6.200000e+00
</td>
<td style="text-align:right;">
1.610000e+01
</td>
<td style="text-align:left;">
▇▅▃▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
OTHER_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.250000e+00
</td>
<td style="text-align:right;">
2.560000e+00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
3.000000e-01
</td>
<td style="text-align:right;">
5.000000e-01
</td>
<td style="text-align:right;">
4.600000e+00
</td>
<td style="text-align:right;">
1.050000e+01
</td>
<td style="text-align:left;">
▇▂▂▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
SOLAR_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.640000e+00
</td>
<td style="text-align:right;">
5.780000e+00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
5.700000e+00
</td>
<td style="text-align:right;">
3.280000e+01
</td>
<td style="text-align:left;">
▇▂▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
STORAGE_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7.000000e-01
</td>
<td style="text-align:right;">
8.500000e-01
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
5.000000e-01
</td>
<td style="text-align:right;">
1.100000e+00
</td>
<td style="text-align:right;">
7.900000e+00
</td>
<td style="text-align:left;">
▇▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
GENERATION_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.000000e+02
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
100.00
</td>
<td style="text-align:right;">
1.000000e+02
</td>
<td style="text-align:right;">
1.000000e+02
</td>
<td style="text-align:right;">
1.000000e+02
</td>
<td style="text-align:right;">
1.000000e+02
</td>
<td style="text-align:left;">
▁▁▇▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
LOW_CARBON_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.578000e+01
</td>
<td style="text-align:right;">
1.306000e+01
</td>
<td style="text-align:right;">
16.40
</td>
<td style="text-align:right;">
3.600000e+01
</td>
<td style="text-align:right;">
4.420000e+01
</td>
<td style="text-align:right;">
5.410000e+01
</td>
<td style="text-align:right;">
8.790000e+01
</td>
<td style="text-align:left;">
▂▇▆▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
ZERO_CARBON_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.235000e+01
</td>
<td style="text-align:right;">
1.208000e+01
</td>
<td style="text-align:right;">
15.50
</td>
<td style="text-align:right;">
3.330000e+01
</td>
<td style="text-align:right;">
4.080000e+01
</td>
<td style="text-align:right;">
5.000000e+01
</td>
<td style="text-align:right;">
8.510000e+01
</td>
<td style="text-align:left;">
▂▇▅▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
RENEWABLE_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.103000e+01
</td>
<td style="text-align:right;">
1.188000e+01
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
1.170000e+01
</td>
<td style="text-align:right;">
1.930000e+01
</td>
<td style="text-align:right;">
2.850000e+01
</td>
<td style="text-align:right;">
6.620000e+01
</td>
<td style="text-align:left;">
▆▇▅▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
FOSSIL_perc
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.339000e+01
</td>
<td style="text-align:right;">
1.290000e+01
</td>
<td style="text-align:right;">
9.00
</td>
<td style="text-align:right;">
3.450000e+01
</td>
<td style="text-align:right;">
4.420000e+01
</td>
<td style="text-align:right;">
5.280000e+01
</td>
<td style="text-align:right;">
7.670000e+01
</td>
<td style="text-align:left;">
▂▅▇▆▁
</td>
</tr>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.017730e+03
</td>
<td style="text-align:right;">
1.290000e+00
</td>
<td style="text-align:right;">
2016.00
</td>
<td style="text-align:right;">
2.017000e+03
</td>
<td style="text-align:right;">
2.018000e+03
</td>
<td style="text-align:right;">
2.019000e+03
</td>
<td style="text-align:right;">
2.020000e+03
</td>
<td style="text-align:left;">
▇▇▇▇▃
</td>
</tr>
<tr>
<td style="text-align:left;">
nHalfHours
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.800000e+01
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
48.00
</td>
<td style="text-align:right;">
4.800000e+01
</td>
<td style="text-align:right;">
4.800000e+01
</td>
<td style="text-align:right;">
4.800000e+01
</td>
<td style="text-align:right;">
4.800000e+01
</td>
<td style="text-align:left;">
▁▁▇▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
GENERATION_MW
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.366393e+04
</td>
<td style="text-align:right;">
7.033020e+03
</td>
<td style="text-align:right;">
18287.00
</td>
<td style="text-align:right;">
2.826400e+04
</td>
<td style="text-align:right;">
3.346200e+04
</td>
<td style="text-align:right;">
3.858925e+04
</td>
<td style="text-align:right;">
5.342700e+04
</td>
<td style="text-align:left;">
▃▇▇▅▁
</td>
</tr>
<tr>
<td style="text-align:left;">
GW
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.366000e+01
</td>
<td style="text-align:right;">
7.030000e+00
</td>
<td style="text-align:right;">
18.29
</td>
<td style="text-align:right;">
2.826000e+01
</td>
<td style="text-align:right;">
3.346000e+01
</td>
<td style="text-align:right;">
3.859000e+01
</td>
<td style="text-align:right;">
5.343000e+01
</td>
<td style="text-align:left;">
▃▇▇▅▁
</td>
</tr>
<tr>
<td style="text-align:left;">
GENERATION_MWh
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.683196e+04
</td>
<td style="text-align:right;">
3.516510e+03
</td>
<td style="text-align:right;">
9143.50
</td>
<td style="text-align:right;">
1.413200e+04
</td>
<td style="text-align:right;">
1.673100e+04
</td>
<td style="text-align:right;">
1.929462e+04
</td>
<td style="text-align:right;">
2.671350e+04
</td>
<td style="text-align:left;">
▃▇▇▅▁
</td>
</tr>
<tr>
<td style="text-align:left;">
GWh
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.683000e+01
</td>
<td style="text-align:right;">
3.520000e+00
</td>
<td style="text-align:right;">
9.14
</td>
<td style="text-align:right;">
1.413000e+01
</td>
<td style="text-align:right;">
1.673000e+01
</td>
<td style="text-align:right;">
1.929000e+01
</td>
<td style="text-align:right;">
2.671000e+01
</td>
<td style="text-align:left;">
▃▇▇▅▁
</td>
</tr>
<tr>
<td style="text-align:left;">
C02e_g
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.292964e+09
</td>
<td style="text-align:right;">
1.993447e+09
</td>
<td style="text-align:right;">
776697500.00
</td>
<td style="text-align:right;">
2.831746e+09
</td>
<td style="text-align:right;">
3.932564e+09
</td>
<td style="text-align:right;">
5.307671e+09
</td>
<td style="text-align:right;">
1.274796e+10
</td>
<td style="text-align:left;">
▆▇▃▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
C02e_kg
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.292964e+06
</td>
<td style="text-align:right;">
1.993447e+06
</td>
<td style="text-align:right;">
776697.50
</td>
<td style="text-align:right;">
2.831746e+06
</td>
<td style="text-align:right;">
3.932564e+06
</td>
<td style="text-align:right;">
5.307671e+06
</td>
<td style="text-align:right;">
1.274796e+07
</td>
<td style="text-align:left;">
▆▇▃▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
C02e_T
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.292960e+03
</td>
<td style="text-align:right;">
1.993450e+03
</td>
<td style="text-align:right;">
776.70
</td>
<td style="text-align:right;">
2.831750e+03
</td>
<td style="text-align:right;">
3.932560e+03
</td>
<td style="text-align:right;">
5.307670e+03
</td>
<td style="text-align:right;">
1.274796e+04
</td>
<td style="text-align:left;">
▆▇▃▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
month
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
6.200000e+00
</td>
<td style="text-align:right;">
3.470000e+00
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
3.000000e+00
</td>
<td style="text-align:right;">
6.000000e+00
</td>
<td style="text-align:right;">
9.000000e+00
</td>
<td style="text-align:right;">
1.200000e+01
</td>
<td style="text-align:left;">
▇▆▅▅▆
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: POSIXct</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
<th style="text-align:left;">
median
</th>
<th style="text-align:right;">
n_unique
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
rDateTimeUTC
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
2016-01-01
</td>
<td style="text-align:left;">
2020-05-31 23:30:00
</td>
<td style="text-align:left;">
2018-03-16 23:45:00
</td>
<td style="text-align:right;">
77184
</td>
</tr>
</tbody>
</table>
</div>
<div id="fuel-trends" class="section level2">
<h2><span class="header-section-number">6.2</span> Fuel trends</h2>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:fuelGWByYear">Table 6.2: </span>Mean half-hourly GW by fuel by year
</caption>
<thead>
<tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:right;">
coal
</th>
<th style="text-align:right;">
gas
</th>
<th style="text-align:right;">
nuclear
</th>
<th style="text-align:right;">
wind
</th>
<th style="text-align:right;">
hydro
</th>
<th style="text-align:right;">
solar
</th>
<th style="text-align:right;">
biomass
</th>
<th style="text-align:right;">
imports
</th>
<th style="text-align:right;">
other
</th>
<th style="text-align:right;">
N obs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2016
</td>
<td style="text-align:right;">
3195.43
</td>
<td style="text-align:right;">
14506.72
</td>
<td style="text-align:right;">
7605.16
</td>
<td style="text-align:right;">
3009.30
</td>
<td style="text-align:right;">
383.93
</td>
<td style="text-align:right;">
1179.91
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
2309.63
</td>
<td style="text-align:right;">
1615.29
</td>
<td style="text-align:right;">
17520
</td>
</tr>
<tr>
<td style="text-align:right;">
2017
</td>
<td style="text-align:right;">
2358.13
</td>
<td style="text-align:right;">
13615.50
</td>
<td style="text-align:right;">
7484.17
</td>
<td style="text-align:right;">
4620.53
</td>
<td style="text-align:right;">
450.90
</td>
<td style="text-align:right;">
1240.04
</td>
<td style="text-align:right;">
254.42
</td>
<td style="text-align:right;">
2222.08
</td>
<td style="text-align:right;">
1396.04
</td>
<td style="text-align:right;">
17472
</td>
</tr>
<tr>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
1756.79
</td>
<td style="text-align:right;">
13155.90
</td>
<td style="text-align:right;">
6921.38
</td>
<td style="text-align:right;">
5633.11
</td>
<td style="text-align:right;">
365.93
</td>
<td style="text-align:right;">
1343.86
</td>
<td style="text-align:right;">
1837.52
</td>
<td style="text-align:right;">
2515.99
</td>
<td style="text-align:right;">
81.57
</td>
<td style="text-align:right;">
17472
</td>
</tr>
<tr>
<td style="text-align:right;">
2019
</td>
<td style="text-align:right;">
679.25
</td>
<td style="text-align:right;">
13074.05
</td>
<td style="text-align:right;">
6023.43
</td>
<td style="text-align:right;">
6641.34
</td>
<td style="text-align:right;">
407.94
</td>
<td style="text-align:right;">
1340.81
</td>
<td style="text-align:right;">
1961.30
</td>
<td style="text-align:right;">
2868.74
</td>
<td style="text-align:right;">
88.56
</td>
<td style="text-align:right;">
17472
</td>
</tr>
<tr>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
840.01
</td>
<td style="text-align:right;">
9623.77
</td>
<td style="text-align:right;">
5548.15
</td>
<td style="text-align:right;">
8659.54
</td>
<td style="text-align:right;">
555.82
</td>
<td style="text-align:right;">
1517.96
</td>
<td style="text-align:right;">
2154.97
</td>
<td style="text-align:right;">
3020.43
</td>
<td style="text-align:right;">
153.53
</td>
<td style="text-align:right;">
7248
</td>
</tr>
</tbody>
</table>
<p>Figure <a href="#fig:fuelTrendPlots"><strong>??</strong></a> shows mean half-hourly generation per month by fuel together with a smoothed trend line. Note that these values are <em>not</em> de-seasoned.</p>
<p>Clearly some of these trends are non-monotonic and so are poorly represented by the Theil-Sen function. The next set of plots repeat this analysis using openair's smoothTrend plot which implemets a GAM-based method similar to <a href="#fig:compareDailyGWhPlot">3.9</a>.</p>
<div class="figure"><span id="fig:smoothTrendPlots1"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-1.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.1: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
<div class="figure"><span id="fig:smoothTrendPlots2"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-2.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.2: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
<div class="figure"><span id="fig:smoothTrendPlots3"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-3.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.3: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
<div class="figure"><span id="fig:smoothTrendPlots4"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-4.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.4: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
<div class="figure"><span id="fig:smoothTrendPlots5"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-5.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.5: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
<div class="figure"><span id="fig:smoothTrendPlots6"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-6.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.6: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
<div class="figure"><span id="fig:smoothTrendPlots7"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-7.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.7: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
<div class="figure"><span id="fig:smoothTrendPlots8"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-8.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.8: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
<div class="figure"><span id="fig:smoothTrendPlots9"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-9.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.9: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
<div class="figure"><span id="fig:smoothTrendPlots10"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/smoothTrendPlots-10.png" alt="Trend plots of mean half-hourly fuel use per month since 2016-01-01" width="672" />
<p class="caption">
Figure 6.10: Trend plots of mean half-hourly fuel use per month since 2016-01-01
</p>
</div>
</div>
<div id="experimental-plots" class="section level2">
<h2><span class="header-section-number">6.3</span> Experimental plots</h2>
<p>Figure <a href="#fig:binedDemand">6.11</a> shows the relationship between half-hourly carbon intensity and half-hourly generation over the last five years. 2020 is excluded as it is not yet complete.</p>
<pre><code>## 
## Attaching package: &#39;gtools&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:drake&#39;:
## 
##     running</code></pre>
<div class="figure"><span id="fig:binedDemand"></span>
<img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/binedDemand-1.png" alt="Box &amp; whiskers plots of carbon intensity over time by generation decile" width="672" />
<p class="caption">
Figure 6.11: Box &amp; whiskers plots of carbon intensity over time by generation decile
</p>
</div>
<p>The openair package <span class="citation">(Carslaw and Ropkins 2012)</span> contains a number of novel plotting methods.</p>
<pre><code>## Warning: `as_data_frame()` is deprecated as of tibble 2.0.0.
## Please use `as_tibble()` instead.
## The signature and semantics have changed, see `?as_tibble`.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_warnings()` to see where this warning was generated.</code></pre>
<pre><code>## Warning: `data_frame()` is deprecated as of tibble 1.1.0.
## Please use `tibble()` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_warnings()` to see where this warning was generated.</code></pre>
<p><img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/carbonRose-1.png" width="672" /></p>
<p><img src="covidLockdown_UK_upTo_2020-06-01_files/figure-html/carbonScatter-1.png" width="672" /></p>
</div>
</div>
<div id="runtime" class="section level1">
<h1><span class="header-section-number">7</span> Runtime</h1>
<p>Analysis completed in 201.47 seconds ( 3.36 minutes) using <a href="https://cran.r-project.org/package=knitr">knitr</a> in <a href="http://www.rstudio.com">RStudio</a> with R version 3.6.0 (2019-04-26) running on x86_64-redhat-linux-gnu.</p>
</div>
<div id="r-environment" class="section level1">
<h1><span class="header-section-number">8</span> R environment</h1>
<div id="r-packages-used" class="section level2">
<h2><span class="header-section-number">8.1</span> R packages used</h2>
<ul>
<li>base R <span class="citation">(R Core Team 2016)</span></li>
<li>bookdown <span class="citation">(Xie 2016a)</span></li>
<li>data.table <span class="citation">(Dowle et al. 2015)</span></li>
<li>drake <span class="citation">(Landau 2019)</span></li>
<li>ggplot2 <span class="citation">(Wickham 2009)</span></li>
<li>kableExtra <span class="citation">(Zhu 2018)</span></li>
<li>knitr <span class="citation">(Xie 2016b)</span></li>
<li>lubridate <span class="citation">(Grolemund and Wickham 2011)</span></li>
<li>rmarkdown <span class="citation">(Allaire et al. 2018)</span></li>
<li>zoo <span class="citation">(Zeileis and Grothendieck 2005)</span></li>
</ul>
</div>
<div id="session-info" class="section level2">
<h2><span class="header-section-number">8.2</span> Session info</h2>
<pre><code>## R version 3.6.0 (2019-04-26)
## Platform: x86_64-redhat-linux-gnu (64-bit)
## Running under: Red Hat Enterprise Linux
## 
## Matrix products: default
## BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
## 
## locale:
##  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
##  [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
##  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
## [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] gtools_3.8.1      openair_2.7-2     kableExtra_1.1.0  zoo_1.8-4         skimr_2.1.1      
##  [6] lubridate_1.7.9   hms_0.5.3         ggplot2_3.3.1     drake_7.12.2      data.table_1.12.0
## [11] gridCarbon_0.1.0  here_0.1         
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.1          txtq_0.2.0          lattice_0.20-38     tidyr_1.1.0        
##  [5] prettyunits_1.0.2   assertthat_0.2.0    rprojroot_1.3-2     digest_0.6.25      
##  [9] utf8_1.1.4          R6_2.3.0            repr_1.1.0          backports_1.1.3    
## [13] evaluate_0.14       highr_0.7           httr_1.4.1          pillar_1.4.4       
## [17] rlang_0.4.6         progress_1.2.2      rstudioapi_0.11     hexbin_1.27.2      
## [21] Matrix_1.2-17       rmarkdown_2.2       labeling_0.3        splines_3.6.0      
## [25] webshot_0.5.2       readr_1.3.1         stringr_1.4.0       igraph_1.2.2       
## [29] munsell_0.5.0       compiler_3.6.0      xfun_0.14           pkgconfig_2.0.2    
## [33] base64enc_0.1-3     mgcv_1.8-28         htmltools_0.3.6     tidyselect_1.1.0   
## [37] tibble_3.0.1        bookdown_0.19       fansi_0.4.0         viridisLite_0.3.0  
## [41] crayon_1.3.4        dplyr_1.0.0         withr_2.1.2         MASS_7.3-51.4      
## [45] grid_3.6.0          nlme_3.1-139        jsonlite_1.6        gtable_0.2.0       
## [49] lifecycle_0.2.0     magrittr_1.5        storr_1.2.1         scales_1.0.0       
## [53] cli_2.0.2           stringi_1.2.4       mapproj_1.2.7       latticeExtra_0.6-28
## [57] xml2_1.3.2          ellipsis_0.3.1      filelock_1.0.2      generics_0.0.2     
## [61] vctrs_0.3.1         RColorBrewer_1.1-2  tools_3.6.0         forcats_0.5.0      
## [65] glue_1.4.1          purrr_0.3.4         maps_3.3.0          parallel_3.6.0     
## [69] yaml_2.2.0          colorspace_1.4-0    cluster_2.0.8       base64url_1.4      
## [73] rvest_0.3.5         knitr_1.28</code></pre>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-rmarkdown">
<p>Allaire, JJ, Yihui Xie, Jonathan McPherson, Javier Luraschi, Kevin Ushey, Aron Atkins, Hadley Wickham, Joe Cheng, and Winston Chang. 2018. <em>Rmarkdown: Dynamic Documents for R</em>. <a href="https://CRAN.R-project.org/package=rmarkdown" class="uri">https://CRAN.R-project.org/package=rmarkdown</a>.</p>
</div>
<div id="ref-openair">
<p>Carslaw, David C., and Karl Ropkins. 2012. “Openair — an R Package for Air Quality Data Analysis.” <em>Environmental Modelling &amp; Software</em> 27–28 (0): 52–61. doi:<a href="https://doi.org/10.1016/j.envsoft.2011.09.008">10.1016/j.envsoft.2011.09.008</a>.</p>
</div>
<div id="ref-data.table">
<p>Dowle, M, A Srinivasan, T Short, S Lianoglou with contributions from R Saporta, and E Antonyan. 2015. <em>Data.table: Extension of Data.frame</em>. <a href="https://CRAN.R-project.org/package=data.table" class="uri">https://CRAN.R-project.org/package=data.table</a>.</p>
</div>
<div id="ref-lubridate">
<p>Grolemund, Garrett, and Hadley Wickham. 2011. “Dates and Times Made Easy with lubridate.” <em>Journal of Statistical Software</em> 40 (3): 1–25. <a href="http://www.jstatsoft.org/v40/i03/" class="uri">http://www.jstatsoft.org/v40/i03/</a>.</p>
</div>
<div id="ref-khan_analysis_2018">
<p>Khan, Imran, Michael W. Jack, and Janet Stephenson. 2018. “Analysis of Greenhouse Gas Emissions in Electricity Systems Using Time-Varying Carbon Intensity.” <em>Journal of Cleaner Production</em> 184 (May): 1091–1101. doi:<a href="https://doi.org/10.1016/j.jclepro.2018.02.309">10.1016/j.jclepro.2018.02.309</a>.</p>
</div>
<div id="ref-drake">
<p>Landau, William Michael. 2019. <em>Drake: A Pipeline Toolkit for Reproducible Computation at Scale</em>. <a href="https://CRAN.R-project.org/package=drake" class="uri">https://CRAN.R-project.org/package=drake</a>.</p>
</div>
<div id="ref-baseR">
<p>R Core Team. 2016. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/" class="uri">https://www.R-project.org/</a>.</p>
</div>
<div id="ref-staffell_measuring_2017">
<p>Staffell, Iain. 2017. “Measuring the Progress and Impacts of Decarbonising British Electricity.” <em>Energy Policy</em> 102 (March): 463–75. doi:<a href="https://doi.org/10.1016/j.enpol.2016.12.037">10.1016/j.enpol.2016.12.037</a>.</p>
</div>
<div id="ref-ggplot2">
<p>Wickham, Hadley. 2009. <em>Ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. <a href="http://ggplot2.org" class="uri">http://ggplot2.org</a>.</p>
</div>
<div id="ref-bookdown">
<p>Xie, Yihui. 2016a. <em>Bookdown: Authoring Books and Technical Documents with R Markdown</em>. Boca Raton, Florida: Chapman; Hall/CRC. <a href="https://github.com/rstudio/bookdown" class="uri">https://github.com/rstudio/bookdown</a>.</p>
</div>
<div id="ref-knitr">
<p>———. 2016b. <em>Knitr: A General-Purpose Package for Dynamic Report Generation in R</em>. <a href="https://CRAN.R-project.org/package=knitr" class="uri">https://CRAN.R-project.org/package=knitr</a>.</p>
</div>
<div id="ref-zoo">
<p>Zeileis, Achim, and Gabor Grothendieck. 2005. “Zoo: S3 Infrastructure for Regular and Irregular Time Series.” <em>Journal of Statistical Software</em> 14 (6): 1–27. doi:<a href="https://doi.org/10.18637/jss.v014.i06">10.18637/jss.v014.i06</a>.</p>
</div>
<div id="ref-kableExtra">
<p>Zhu, Hao. 2018. <em>KableExtra: Construct Complex Table with ’Kable’ and Pipe Syntax</em>. <a href="https://CRAN.R-project.org/package=kableExtra" class="uri">https://CRAN.R-project.org/package=kableExtra</a>.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
